version: "3.7"
services:
  app-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: "nlperri/cabeceira-api:latest"
    restart: always
    ports:
      - "8081:8081"
    networks:
      - springapipostgres-net
    env_file:
      - .env
    volumes:
      - ".m2:/root/.m2"
    environment:
      - SPRING_DATASOURCE_URL=${{ secrets.DB_URL }}
      - SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }}
      - SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}
      - API_SECURITY_TOKEN_SECRET=${{ secrets.JWT_SECRET }}
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    restart: always
    ports:
      - "6869:8081"
    networks:
      - springapipostgres-net
    environment:
      - SPRING_PROFILES_ACTIVE=test
    volumes:
      - ".m2:/root/.m2"
networks:
  springapipostgres-net:
